# Generated by Django 2.1.5 on 2019-01-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=50)),
                ('queen_year', models.IntegerField(default=2019)),
                ('hive_from', models.CharField(default='', max_length=50)),
                ('queen_from', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=50)),
                ('brood_boxes', models.IntegerField(default=1)),
                ('supers', models.IntegerField(default=1)),
                ('queen_breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hives.Breed')),
            ],
        ),
    ]
