# Generated by Django 2.1.5 on 2019-01-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hive',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
