# Generated by Django 2.1.5 on 2019-01-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0003_hive_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='hive_from',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hive',
            name='queen_from',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
