# Generated by Django 2.1.5 on 2019-02-03 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0004_auto_20190131_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='hive',
            name='location',
        ),
        migrations.AlterField(
            model_name='hive',
            name='supers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pallet',
            name='yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hives.Yard'),
        ),
    ]
