# Generated by Django 2.1.5 on 2019-02-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0005_auto_20190203_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='pallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hives.Pallet'),
        ),
    ]
